services:
  backend:
    build:
      context: .
      dockerfile: apps/backend/Dockerfile.dev
    volumes:
      - ./apps/backend:/app/apps/backend
      - /app/apps/backend/node_modules
    ports:
      - "8000:8000"
    networks:
      - app_network
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:8000/', (res) => process.exit(res.statusCode === 200 ? 0 : 1))"]
      interval: 100s
      timeout: 5s
      retries: 3
      start_period: 20s

  frontend:
    build:
      context: .
      dockerfile: apps/frontend/Dockerfile.dev
    volumes:
      - ./apps/frontend:/app/apps/frontend
      - /app/apps/frontend/node_modules
    ports:
      - "3174:3174"
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
